### ISSUE TITLE
add the scss toolchain to git

### ISSUE THREAD

**Issue by kijanawoodard** [zeal-dev/zeal-website#147]
so there is a way to update the styles without out of band knowledge

**Comment by kijanawoodard** [comment]
Or remove sass. Can we do it all with css variables?

**Comment by joeyguerra** [comment]
Yes.

**Comment by joeyguerra** [comment]
can't we just delete all the .scss files?

**Comment by 18nguyenl** [comment]
I think it's possible. Only concern is that some styling is done specifically on top of SCSS mixins. Also, there's a lot of CSS in general. Gonna need to find a way to organize. That main CSS file is scary big.
